[package]
name = "rust-fractals"
version = "0.1.0"
edition = "2021"
authors = ["Sergio Flores <sergio@saft.industries>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
num-complex = "0.4.2"
